FROM gitlab-registry.in2p3.fr/fbi-data/dockers-projects/omero-web/omero-web:latest
USER root
COPY omero-dash-webapp/omerodash /opt/omero/web/venv3/lib/python3.8/site-packages/omerodash
COPY omero-dash-webapp/config.omero  /opt/omero/web/config/config.omero