FROM gitlab-registry.in2p3.fr/fbi-data/dockers-projects/omero-web/omero-web:latest
#USER omero-web
RUN /opt/omero/server/venv3/bin/pip install git+https://github.com/juliomateoslangerak/dash-omero-project.git